---
version: 2

updates:
  # GitHub Actions updates.
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(gh):"
      include: "scope"
    labels:
      - "chore"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"

  # Node.js dependencies updates.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    labels:
      - "chore"
      - "dependencies"
    groups:
      development-dependencies:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # Docker image updates.
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(docker):"
      include: "scope"
    labels:
      - "chore"
      - "docker"
    groups:
      docker-updates:
        patterns:
          - "*"
